name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          echo "Running tests (placeholder)"
          # pytest or any test command

      - name: Build Docker Image
        run: |
          docker build -t devops-demo .

      - name: Deploy to EC2 (or Render)
        run: |
          echo "Deploy step here"
          # You’ll add deployment commands in the next phase
